
[package]
name = "plugin_lol_matchmaking"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest ="0.12"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
common = { path = "../common" }
